### PR TITLE
Restore session tokens after reset

### PR DESCRIPTION
**Pull request by grappler**
fixes #14

It worked for me on my local testing environment. I am unsure if this will work on older versions of WordPress as I think the session management was only included recently.

### CODE REVIEW

**Comment by chrisberthe** [comment]
Do you know the minimum version? I don't have a problem with bumping it up... Think it's time anyway.

**Comment by grappler** [comment]
It looks like it was inttroduced in WP 4.0 https://developer.wordpress.org/reference/classes/wp_session_tokens/ This looks like a rewrite then a new feature. There must have been another system for it before it so it might still work.

I am testing it on WP 3.8.11 now.

**Comment by grappler** [comment]
You need to increase the minimum version to WP 4.2 as that is when  `wp_install_maybe_enable_pretty_permalinks` was added.

**Comment by chrisberthe** [comment]
Two things while I'm testing:

1. From where is `wp_install_maybe_enable_pretty_permalinks` being called?
2. This doesn't quite fix the issue we have with the command line where it'll still log out the user if their currently in the dashboard and you call `wp reset database --tables='users'`. Think you can integrate that?

**Comment by chrisberthe** [comment]
It's basically when you reset the `usermeta` table, either within the dashboard or the command line, that it logs the user out.

**Comment by chrisberthe** [comment]
I also answered my own question about `wp_install_maybe_enable_pretty_permalinks`... it's being called within the `wp_install` function.

**Comment by chrisberthe** [comment]
The `set_user_session_tokens` method was being called too late. I updated it and it works.

Cool thing is if the first administrator (user with an ID of 1) is logged into the admin panel, but decides to use the command line to reset the database, they won't be logged out.

Hopefully I'm not missing anything test-wise, but it should be working again.

Thank you @grappler.

**Pull request merged**
